version: '3.3'
services:
  portal:
    restart: always
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
     - "5060:5000"
    volumes:
      - "./webapp/cpro_common:/usr/src/app"
    links:
      - dhair2-db
      - cpro-common-db
    container_name: cpro-common
    stdin_open  : true
    tty: true
    depends_on:
      - cpro-common-db
      - dhair2-db
    environment:
      WAIT_HOSTS: cpro-common-db:3306, dhair2-db:3306
      WAIT_BEFORE_HOSTS: 10
      FLASK_APP: "cpro_common.py"
      FLASK_DEBUG: 1
      AUTHLIB_INSECURE_TRANSPORT: 'true'
      MODE: 'dev'
    networks:
      - cpro-common
  dhair2-db:
    restart: always
    image: mysql:5.7
    hostname: dhair2-db
    volumes:
      - "./db/sql/dhair2-db:/docker-entrypoint-initdb.d"
      - type: volume
        source: dhair2-db
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    container_name: dhair2-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dhair2_demo
      MYSQL_USER: dhair
      MYSQL_PASSWORD: dhair
    networks:
      - cpro-common
  cpro-common-db:
    restart: always
    image: mysql:5.7
    hostname: cpro-common-db
    volumes:
      - "./db/sql/cpro-common-db:/docker-entrypoint-initdb.d"
      - type: volume
        source: cpro-common-db
        target: /var/lib/mysql
    ports:
      - "3307:3306"
    container_name: cpro-common-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cpro_common  
      MYSQL_USER: cpro
      MYSQL_PASSWORD: cpro
    networks:
      - cpro-common
volumes:
  cpro-common-db:
  dhair2-db:
networks:
  cpro-common:
